---
# Migration to PHP 7.1 (as dotdeb won't be supporting new versions).
#===================================================================

- name: Remove repository for Debian dotdeb
  apt_repository: repo="deb http://packages.dotdeb.org {{ ansible_distribution_release }} all" state=absent

- name: Remove apt key for Debian dotdeb
  apt_key: id=89DF5277 state=absent

- name: Remove PHP 5.x Packages
  apt:
    name: "php5-*"
    state: absent

- name: Remove PHP 7.0 Packages
  apt:
    name: "php7.0-*"
    state: absent
