---
- include: dotdeb-uninstall.yml

- include: sury-install.yml

- name: Update apt
  apt: update_cache=yes

- name: Install PHP Packages
  apt: pkg={{ php_packages }} state=latest
  when: php_packages is defined
  notify:
    - restart php7-fpm

- name: Write custom php.ini
  template: src=php.ini.j2 dest=/etc/php/7.1/fpm/php.ini owner=root mode=0644
  notify:
    - restart php7-fpm

- name: Write custom php-fpm.conf
  template: src=php-fpm.conf.j2 dest=/etc/php/7.1/fpm/php-fpm.conf owner=root mode=0644
  notify:
    - restart php7-fpm
