---
- name: Add apt key for Debian sury
  apt_key: url=https://packages.sury.org/php/apt.gpg state=present

- name: Download php.gpg
  get_url:
    url: https://packages.sury.org/php/apt.gpg
    dest: /etc/apt/trusted.gpg.d/php.gpg
    mode: 0640

- name: Add alternative php repo
  apt_repository: repo="deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main" state=present
